applicationName: Stash Backend
isAppCreationOpen: true
appsTokenStoreKey: verySecretTokenKeyForAppsTokenStore
database:
  url: jdbc:postgresql://localhost:5432/yourdb
  user: yourUser
  password: yourPassword
  minSize: 8
  maxSize: 32
  driverClass: org.postgresql.Driver
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  properties:
    charSet: UTF-8
